apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ix-go-xapp
  labels:
    app: ix-go-xapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ix-go-xapp
  template:
    metadata:
      labels:
        app: ix-go-xapp
    spec:
      containers:
        - name: ix-go-xapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
